//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbanZonesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceOrder
    {
        public string OrderId { get; set; }
        public string UserId { get; set; }
        public string ServiceProblemId { get; set; }
        public int ServiceItemId { get; set; }
        public string AcceptBy { get; set; }
        public Nullable<decimal> Amout { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
