//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbanZonesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceProblem
    {
        public string Id { get; set; }
        public Nullable<int> ServiceItemId { get; set; }
        public Nullable<System.DateTime> DateOfAvailibility { get; set; }
        public Nullable<decimal> PreferredAmount { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
